### ISSUE TITLE
OOM on the single A100

### ISSUE THREAD

**Issue by MikeChenfu** [hpcaitech/OPT-Benchmark#13]
Hello guys, I am trying to reproduce the result listed in this repository. However, I got OOM on the script of run_opt_clm.sh and run_opt_clm_colossalai.sh if the BS is set as 12 or 24. Appreciate it if you have any suggestions.

**Comment by feifeibear** [comment]
Thanks, I will have a look.

**Comment by ZijianYY** [comment]
I tested this code on my environment and it works fine without the above errors. It is recommended that you follow this link https://github.com/hpcaitech/OPT-Benchmark to check the environment installation. I believe that you should be able to run normally when the environment is configured correctly.

**Comment by MikeChenfu** [comment]
@feifeibear @ZijianYY Thanks for the testing. I'll rebuild my environment and test them again.
