### ISSUE TITLE
bug: `invalid requirement: 'accelerate==0.10.0,'``

### ISSUE THREAD

**Issue by MEllis-github** [hpcaitech/OPT-Benchmark#7]
### Summary
Following https://github.com/hpcaitech/OPT-Benchmark#run-benchmarking, leads to the following error due to the requirement specification `pip install accelerate==0.10.0, datasets==1.18.4, transformers==4.21.0, deepspeed==0.6.5 tqdm`

```
ERROR: Invalid requirement: 'accelerate==0.10.0,'
```

### Additional Notes
Using image: https://github.com/orgs/hpcaitech/packages/container/pytorch-cuda/42358580?tag=1.12.0-11.3.0

### Files
* https://github.com/hpcaitech/OPT-Benchmark/blob/main/README.md

**Comment by MEllis-github** [comment]
I will PR my local fix

**Comment by Cypher30** [comment]
Thanks a lot for your PR!!
