### ISSUE TITLE
bug: `run_gpt_clm.sh: No such file or directory`

### ISSUE THREAD

**Issue by MEllis-github** [hpcaitech/OPT-Benchmark#8]
### Summary
Following https://github.com/hpcaitech/OPT-Benchmark#run-benchmarking, leads to the following error, assumably due to the renaming of run_gpt_clm.sh.

```
bash: ./run_gpt_clm.sh: No such file or directory
```

### Files
* https://github.com/hpcaitech/OPT-Benchmark/blob/main/README.md

**Comment by MEllis-github** [comment]
I will PR my fix assuming `run_gpt_clm.sh` --> [run_opt_clm.sh](https://github.com/hpcaitech/OPT-Benchmark/blob/main/run_opt_clm.sh)

**Comment by Cypher30** [comment]
Thanks a lot for your PR!!
